<html>
<head>
    <title>Home</title>
    <link media="screen,projection" type="text/css" href="/static/css/lib" rel="Stylesheet">

    <!-- 1140px Grid styles for IE -->
	<!--[if lte IE 9]><link rel="stylesheet" href="/static/css/lib/1140grid/ie.css" type="text/css" media="screen" /><![endif]-->

	<!-- The 1140px Grid - http://cssgrid.net/ -->
	<link rel="stylesheet" href="/static/css/lib/1140grid/1140.css" type="text/css" media="screen" />

    <script src="/static/js/lib/jquery/jquery-1.7.1.min.js"></script>
</head>

<body id="home">
    <h1>$welcome$</h1>
    <div id="container">
        <form action="" method="post">
            <input type="text" name="username" />
            <input type="password" name="password" />
        </form>
    </div>
</body>
</html>