<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="index, follow">
    <meta name="description" content="Futbal - live výsledky, aktuálne futbalové zápasy a turnaje. Domáce a zahraničné futbalové ligy. Výsledky a tabuľky z futbalu na Šport.sk." />
    <meta name="keywords" content="live, výsledky, zápasy,Futbal" />
    <meta name="copyright" content="SPORT.SK, s.r.o. & Azet.sk, a. s." />
    <meta name="author" content="SPORT.SK, s.r.o. & Azet.sk, a. s." />

    <title>$messages.("decorator.title")$ - $title$</title>

    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/css/site.css" rel="stylesheet">
    <!--<link href="/static/css/copy.css" rel="stylesheet">--> <!-- copy of azet -->


    $head;format="none"$
</head>
<body class='$page.properties.("body.class")$' style="">

    $body;format="none"$

</body>
</html>