<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap.docs.css" rel="stylesheet" media="screen">
    <link href="/static/css/daterangepicker.css" rel="stylesheet" media="screen">
    <link href="/static/css/application.css" rel="stylesheet" media="screen">

    $head;format="none"$

    <title>$title$</title>
</head>
<body class='$page.properties.("body.class")$' style="" data-spy="scroll" data-target=".bs-docs-sidebar">

<div class="container-fluid">
    $top_navigator()$

    $body;format="none"$
</div>

<script src="http://code.jquery.com/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/moment.min.js"></script>
<script src="/static/js/daterangepicker.js"></script>
</body>
</html>