<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#" name="top">Sport Betting Analytics</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="/roger/betting/betfair/dashboard"><i class="icon-home"></i> Dashboard</a></li>
                    <li class="divider-vertical"></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-signal"></i> Graphs <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a>Settings</a></li>
                            <!--<li class="divider"></li>-->
                            <li><a>Logout</a></li>
                        </ul>
                    </li>
                    <li class="divider-vertical"></li>
                    <li><a href="#"><i class="icon-envelope"></i> Actions</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="#"><i class="icon-signal"></i> Stats</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="#"><i class="icon-lock"></i> Players</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="#"><i class="icon-lock"></i> Goals</a></li>
                    <li class="divider-vertical"></li>
                </ul>
                <div class="btn-group pull-right">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user"></i> admin	<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="icon-share"></i> Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>