<html>
<head>
    <link rel="stylesheet" href="reset.css" type="text/css" media="screen"/>
    <link rel="stylesheet" href="sub-event-list.css" type="text/css" media="screen"/>

    <link rel="stylesheet" href="1140grid/1140.css" type="text/css" media="screen"/>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="sevencol" style="border-bottom: 1px solid #cccccc; margin-bottom: 10px; font-size: 1.2em; font-weight: bold;">
          <h1>12.01.2012 - Today</h1>
        </div>
    </div>
    <div class="row">
        <div class="box sevencol">
            <div class="header">
                <h2>Australian Open</h2>
            </div>
            <div class="matches">
                <table>
                    <tbody>
                    <tr>
                        <td class="time live">Live</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1.6</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">16:00</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1000</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">Live</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1.6</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">16:00</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1000</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    </tbody>
                </table>
            </div>  
        </div>
    </div>
    
    <div class="row">
        <div class="box sevencol">
            <div class="header">
                <h2>Australian Open</h2>
            </div>
            <div class="matches">
                <table>
                    <tbody>
                    <tr>
                        <td class="time live">Live</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1.6</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">16:00</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1000</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">Live</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1.6</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">16:00</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1000</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    </tbody>
                </table>
            </div>  
        </div>
    </div>
    
    <div class="row">
        <div class="box sevencol">
            <div class="header">
                <h2>Australian Open</h2>
            </div>
            <div class="matches">
                <table>
                    <tbody>
                    <tr>
                        <td class="time live">Live</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1.6</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">16:00</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1000</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">Live</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1.6</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    <tr>
                        <td class="time live">16:00</td>
                        <td class="homeTeam ">Nadal</td>
                        <td class="homePrice center">1000</td>

                        <td class="awayTeam ">Federer</td>
                        <td class="awayPrice center">2.5</td>
                        <td class="moreMarkets">+16</td>
                    </tr>
                    </tbody>
                </table>
            </div>  
        </div>
    </div>
</div>
</body>
