<html>
<head>
    <title>Home</title>

    <!-- 1140px Grid styles for IE -->
	<!--[if lte IE 9]><link rel="stylesheet" href="/static/css/lib/1140grid/ie.css" type="text/css" media="screen" /><![endif]-->

	<!-- The 1140px Grid - http://cssgrid.net/ -->
	<link rel="stylesheet" href="/static/css/lib/1140grid/1140.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/static/css/login-form.css" type="text/css" media="screen" />

    <script src="/static/js/lib/jquery/jquery-1.7.1.min.js"></script>
</head>

<body id="home">
    <h1>Betfair Menu</h1>
    <div id="container">
        <ul>
            <li><a href="/betfair/account/balance">Account Balance</a></li>
            <li><a hreg="/betfair/login">login</a></li>
            <li><a href="/betfair/logout">logout</a></li>
            <li><a href="#">Replicate Account Statement</a></li>
            <li><a href="#">Generate Daily Betting Report</a></li>
            <li><a href="#">Generate Weekly Betting Report</a></li>
            <li><a href="#">Generate Monthly Betting Report</a></li>
            <li><a href="#">Display overall betting statistics</a></li>
        </ul>
    </div>
</body>
</html>