<html>
<head>
    <title>Daily Betting Report</title>
</head>

<body>
    <div id="container">
        <form action="/betfair/daily-betting-report" method="post">
            <label for="startDate">Report Date:</label>
            <input id="startDate" type="text" name="reportDate" value=""/>
            <button>
                <span>Create</span>
            </button>
        </form>
    </div>
</body>
</html>