<html>
<head>
    <title>Betfair Data Replication</title>

    <script src="/static/js/lib/jquery/jquery-1.7.1.min.js"></script>
    <script src="/static/js/lib/underscore-min-1.3.1.js"></script>
    <script src="/static/js/lib/backbone-min-0.9.1.js"></script>
</head>

<body id="home">
    <ul class="replications">
        <li>
            <a href="/betfair/today-market-replication">Replicate Today's Markets</a>
        </li>
    </ul>

<script src="/static/js/modules/ManualDataReplication/js/manualDataReplicationModule.js"></script>
</body>
</html>